{
 "title": "原神小幫手",
 "description": "原神小幫手 Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(discordbot_connected, job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Command Count",
   "type": "bargauge",
   "description": "Since last reboot",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(command) (discordbot_on_command_events_total{job=\"$job\"})",
     "legendFormat": "{{command}}"
    },
    {
     "expr": "sum by(command) (discordbot_on_interaction_events_total{job=\"$job\", command!=\"None\"})",
     "legendFormat": "{{command}}"
    },
    {
     "expr": "sum by(interaction) (discordbot_on_interaction_events_total{job=\"$job\", command=\"None\"})",
     "legendFormat": "{{interaction}}"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "discordbot_users_total", "legendFormat": "__auto" },
    {
     "expr": "discordbot_guilds_total{job=\"$job\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "discordbot_channels_total{job=\"$job\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "discordbot_commands_total{job=\"$job\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "time() - discordbot_process_start_time_seconds{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connection Over Time",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "discordbot_connected{job=~\"$job\", shard=\"None\"}",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "discordbot_connected{job=~\"$job\",shard=~'[0-9]+'}",
     "legendFormat": "{{job}} : {{shard}}"
    }
   ]
  },
  {
   "title": "Guilds Over Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "targets": [
    {
     "expr": "discordbot_guilds_total{job=~\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Discord Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "discordbot_latency_seconds{job=~\"$job\", shard=~\"[0-9]+\"}",
     "legendFormat": "{{job}} : {{shard}}"
    },
    {
     "expr": "discordbot_latency_seconds{job=~\"$job\", shard=\"None\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Command Activity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "round(sum by(job, command) (rate(discordbot_on_command_events_total{job=~\"$job\"}[1m])) * 45, 1)",
     "legendFormat": "{{command}}"
    },
    {
     "expr": "round(sum by(job, interaction) (rate(discordbot_on_interaction_events_total{job=~\"$job\", command=~\"None\"}[1m])) * 45, 1)",
     "legendFormat": "{{interaction}}"
    },
    {
     "expr": "round(sum by(job, command) (rate(discordbot_on_interaction_events_total{job=~\"$job\", command!=\"None\"}[1m])) * 45, 1)",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "title": "Channels Over Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "targets": [
    {
     "expr": "discordbot_channels_total{job=~\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "discordbot_cpu_usage_percent{job=~\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Users Over Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 18 },
   "targets": [
    {
     "expr": "discordbot_users_total{job=~\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "discordbot_memory_usage_percent{job=\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Scrape Duration",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "scrape_duration_seconds{job=~\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}