"""增加星鐵忘卻之庭Table

Revision ID: 0deac4be9347
Revises: ff5dbf6e00bb
Create Date: 2023-09-17 22:34:43.120635

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0deac4be9347"
down_revision = "ff5dbf6e00bb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "starrail_forgotten_hall",
        sa.Column("discord_id", sa.Integer(), nullable=False),
        sa.Column("season", sa.Integer(), nullable=False),
        sa.Column("_raw_data", sa.LargeBinary(), nullable=False),
        sa.PrimaryKeyConstraint("discord_id", "season"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("starrail_forgotten_hall")
    # ### end Alembic commands ###
