"""增加未定事件簿每日簽到

Revision ID: 5d2af112b1f5
Revises: fb6f7c8b91f2
Create Date: 2024-01-28 19:55:54.358763

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5d2af112b1f5"
down_revision = "fb6f7c8b91f2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("schedule_daily_checkin", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("has_themis", sa.Boolean(), nullable=False, server_default=sa.text("FALSE"))
        )
        batch_op.add_column(
            sa.Column(
                "has_themis_tw", sa.Boolean(), nullable=False, server_default=sa.text("FALSE")
            )
        )
    op.add_column("users", sa.Column("cookie_themis", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("cookie_themis")

    with op.batch_alter_table("schedule_daily_checkin", schema=None) as batch_op:
        batch_op.drop_column("has_themis_tw")
        batch_op.drop_column("has_themis")

    # ### end Alembic commands ###
