"""baseline

Revision ID: 8565662aa3e0
Revises:
Create Date: 2023-07-22 15:27:29.260833

"""

# revision identifiers, used by Alembic.
revision = "8565662aa3e0"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
