"""add check_daily_training_time

Revision ID: ab959d5054b5
Revises: 8565662aa3e0
Create Date: 2023-07-22 16:31:10.439054

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ab959d5054b5"
down_revision = "8565662aa3e0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "starrail_schedule_notes",
        sa.Column("check_daily_training_time", sa.DateTime(), nullable=True),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("starrail_schedule_notes", schema=None) as batch_op:
        batch_op.drop_column("check_daily_training_time")

    # ### end Alembic commands ###
