"""增加絕區零自動檢查即時便箋資料表

Revision ID: b446593bd37f
Revises: dd20ae39e68a
Create Date: 2024-07-07 12:15:15.183452

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b446593bd37f"
down_revision = "dd20ae39e68a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "zzz_schedule_notes",
        sa.Column("discord_id", sa.Integer(), nullable=False),
        sa.Column("discord_channel_id", sa.Integer(), nullable=False),
        sa.Column("next_check_time", sa.DateTime(), nullable=True),
        sa.Column("threshold_battery", sa.Integer(), nullable=True),
        sa.Column("check_daily_engagement_time", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("discord_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("zzz_schedule_notes")
    # ### end Alembic commands ###
