"""使用者與每日簽到資料表增加絕區零欄位

Revision ID: dd20ae39e68a
Revises: 23942a12b637
Create Date: 2024-07-06 11:02:42.047506

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "dd20ae39e68a"
down_revision = "23942a12b637"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("schedule_daily_checkin", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("has_zzz", sa.Boolean(), nullable=False, server_default=sa.text("FALSE"))
        )

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("cookie_zzz", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("uid_zzz", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("uid_zzz")
        batch_op.drop_column("cookie_zzz")

    with op.batch_alter_table("schedule_daily_checkin", schema=None) as batch_op:
        batch_op.drop_column("has_zzz")

    # ### end Alembic commands ###
