"""增加星鐵虛構敘事table

Revision ID: fb6f7c8b91f2
Revises: 0deac4be9347
Create Date: 2024-01-28 16:04:54.353325

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "fb6f7c8b91f2"
down_revision = "0deac4be9347"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "starrail_pure_fiction",
        sa.Column("discord_id", sa.Integer(), nullable=False),
        sa.Column("season", sa.Integer(), nullable=False),
        sa.Column("_raw_data", sa.LargeBinary(), nullable=False),
        sa.PrimaryKeyConstraint("discord_id", "season"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("starrail_pure_fiction")
    # ### end Alembic commands ###
