"""增加星鐵即時便箋檢查項目: 模擬宇宙、歷戰餘響

Revision ID: ff5dbf6e00bb
Revises: ab959d5054b5
Create Date: 2023-09-02 11:02:56.565028

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ff5dbf6e00bb"
down_revision = "ab959d5054b5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "starrail_schedule_notes", sa.Column("check_universe_time", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "starrail_schedule_notes", sa.Column("check_echoofwar_time", sa.DateTime(), nullable=True)
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("starrail_schedule_notes", schema=None) as batch_op:
        batch_op.drop_column("check_echoofwar_time")
        batch_op.drop_column("check_universe_time")

    # ### end Alembic commands ###
